version: '3'

services:
    web:
        build: .
        restart: always
        ports:
            - "4000:4000"
        volumes:
            - ./locale:/locale
            - ./logs:/logs
            - ./scripts:/scripts